name: "Setup AltWalker"
description: "Set up AltWalker and the GraphWalker command-line tools."
branding:
  icon: "git-pull-request"
  color: "green"
inputs:
  altwalker-version:
    description: "The version of a AltWalker to use, using SemVer's version syntax."
    default: "0.3.0"
  graphwalker-version:
    description: "The version of a GraphWalker to use, using SemVer's version syntax."
    default: "4.3.1"
runs:
  using: "composite"
  steps:
    - name: Set up GraphWalker ${{ inputs.graphwalker-version }}
      run: ${{ github.action_path }}/install_graphwalker.sh ${{ inputs.graphwalker-version }}
      shell: bash
    - name: Set up AltWalker ${{ inputs.altwalker-version }}
      run: ${{ github.action_path }}/install_altwalker.sh ${{ inputs.altwalker-version }}
      shell: bash
